tessearct_path: "C:\\Program Files\\Tesseract-OCR\\tesseract"
captures_path: "project//tweetcaptures/"
model_path: "project//first_model.pickle"
lang: "en"
# twitter tokens:
bearer_token: "" # input your own if you want to generate any training data yourself.
